spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dokunyshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        #        show_sql: true
        format_sql: true
#        osiv 관련
#    open-in-view: false


  profiles:
    include: oauth

# Hibernate log
logging.level:
  org.hibernate.SQL: debug
